-- Use the database
USE smartcooking;

-- Fill the database based on ISO 639-1
CALL insert_language('aa', 'Afar', 'Qafar af');
CALL insert_language('ab', 'Abkhazian', 'Аҧсуа');
CALL insert_language('af', 'Afrikaans', 'Afrikaans');
CALL insert_language('ak', 'Akan', 'Ákán');
CALL insert_language('am', 'Amharic', 'አማርኛ');
CALL insert_language('an', 'Aragonese', 'Aragonés');
CALL insert_language('ar', 'Arabic', 'اَلْعَرَبِيَّةُ');
CALL insert_language('as', 'Assamese', 'অসমীয়া');
CALL insert_language('av', 'Avaric', 'Авар мацӏ');
CALL insert_language('ay', 'Aymara', 'Aymara');
CALL insert_language('az', 'Azerbaijani', 'Azərbaycan dili');
CALL insert_language('ba', 'Bashkir', 'Башҡорт теле');
CALL insert_language('be', 'Belarusian', 'Беларуская мова');
CALL insert_language('bg', 'Bulgarian', 'Български');
CALL insert_language('bi', 'Bislama', 'Bislama');
CALL insert_language('bm', 'Bambara', 'ߓߡߊߣߊ߲ߞߊ߲');
CALL insert_language('bn', 'Bengali', 'বাংলা');
CALL insert_language('bo', 'Tibetan', 'བོད་སྐད་');
CALL insert_language('br', 'Breton', 'Brezhoneg');
CALL insert_language('bs', 'Bosnian', 'Босански');
CALL insert_language('ca', 'Catalan', 'Català');
CALL insert_language('ce', 'Chechen', 'Нохчийн мотт');
CALL insert_language('ch', 'Chamorro', "Finu' Chamoru");
CALL insert_language('co', 'Corsican', 'Corsu');
CALL insert_language('cr', 'Cree', 'ᓀᐦᐃᔭᐍᐏᐣ');
CALL insert_language('cs', 'Czech', 'Čeština');
CALL insert_language('cu', 'Church Slavic', 'Славе́нскїй ѧ҆зы́къ');
CALL insert_language('cv', 'Chuvash', 'Чӑвашла');
CALL insert_language('cy', 'Welsh', 'Cymraeg');
CALL insert_language('da', 'Danish', 'Dansk');
CALL insert_language('de', 'German', 'Deutsch');
CALL insert_language('dv', 'Divehi', 'ދިވެހި');
CALL insert_language('dz', 'Dzongkha', 'རྫོང་ཁ');
CALL insert_language('ee', 'Ewe', 'Èʋegbe');
CALL insert_language('el', 'Greek', 'Ελληνικά');
CALL insert_language('en', 'English', 'English');
CALL insert_language('eo', 'Esperanto', 'Esperanto');
CALL insert_language('es', 'Spanish', 'Español');
CALL insert_language('et', 'Estonian', 'Eesti keel');
CALL insert_language('eu', 'Basque', 'Euskara');
CALL insert_language('fa', 'Persian', 'فارسی');
CALL insert_language('ff', 'Fulah', 'Fulfulde');
CALL insert_language('fi', 'Finnish', 'Suomi');
CALL insert_language('fj', 'Fijian', 'Na Vosa Vakaviti');
CALL insert_language('fo', 'Faroese', 'Føroyskt');
CALL insert_language('fr', 'French', 'Français');
CALL insert_language('fy', 'Western Frisian', 'Frysk');
CALL insert_language('ga', 'Irish', 'Gaeilge');
CALL insert_language('gd', 'Scottish Gaelic', 'Gàidhlig');
CALL insert_language('gl', 'Galician', 'Galego');
CALL insert_language('gn', 'Guarani', "Avañe'ẽ");
CALL insert_language('gu', 'Gujarati', 'ગુજરાતી');
CALL insert_language('gv', 'Manx', 'Gaelg');
CALL insert_language('ha', 'Hausa', 'هَرْشٜن هَوْس');
CALL insert_language('he', 'Hebrew', 'עברית');
CALL insert_language('hi', 'Hindi', 'हिन्दी');
CALL insert_language('ho', 'Hiri Motu', 'Hiri Motu');
CALL insert_language('hr', 'Croatian', 'Hrvatski');
CALL insert_language('ht', 'Haitian', 'Kreyòl ayisyen');
CALL insert_language('hu', 'Hungarian', 'Magyar nyelv');
CALL insert_language('hy', 'Armenian', 'Հայերեն');
CALL insert_language('hz', 'Herero', 'Otjiherero');
CALL insert_language('ia', 'Interlingua', 'Interlingua');
CALL insert_language('id', 'Indonesian', 'Bahasa Indonesia');
CALL insert_language('ie', 'Interlingue', 'Interlingue');
CALL insert_language('ig', 'Igbo', 'ásụ̀sụ́ Ìgbò');
CALL insert_language('ii', 'Sichuan Yi', 'ꆈꌠꉙ');
CALL insert_language('ik', 'Inupiaq', 'Iñupiaq');
CALL insert_language('io', 'Ido', 'Ido');
CALL insert_language('is', 'Icelandic', 'Íslenska');
CALL insert_language('it', 'Italian', 'Italiano');
CALL insert_language('iu', 'Inuktitut', 'ᐃᓄᒃᑎᑐᑦ');
CALL insert_language('ja', 'Japanese', '日本語');
CALL insert_language('jv', 'Javanese', 'ꦧꦱꦗꦮ');
CALL insert_language('ka', 'Georgian', 'ქართული');
CALL insert_language('kg', 'Kongo', 'Kikongo');
CALL insert_language('ki', 'Kikuyu', 'Gĩgĩkũyũ');
CALL insert_language('kj', 'Kuanyama', 'Oshikwanyama');
CALL insert_language('kk', 'Kazakh', 'Қазақша');
CALL insert_language('kl', 'Kalaallisut', 'Kalaallisut');
CALL insert_language('km', 'Khmer', 'ខេមរភាសា');
CALL insert_language('kn', 'Kannada', 'ಕನ್ನಡ');
CALL insert_language('ko', 'Korean', '한국어');
CALL insert_language('kr', 'Kanuri', 'Kanuri');
CALL insert_language('ks', 'Kashmiri', 'कश्मीरी');
CALL insert_language('ku', 'Kurdish', 'Kurdî');
CALL insert_language('kv', 'Komi', 'Коми кыв');
CALL insert_language('kw', 'Cornish', 'Kernewek');
CALL insert_language('ky', 'Kirghiz', 'Кыргызча');
CALL insert_language('la', 'Latin', 'Latinum');
CALL insert_language('lb', 'Luxembourgish', 'Lëtzebuergesch');
CALL insert_language('lg', 'Ganda', 'Luganda');
CALL insert_language('li', 'Limburgish', 'Limburgs');
CALL insert_language('ln', 'Lingala', 'Lingála');
CALL insert_language('lo', 'Lao', 'ພາສາລາວ');
CALL insert_language('lt', 'Lithuanian', 'Lietuviškai');
CALL insert_language('lu', 'Luba-Katanga', 'Kiluba');
CALL insert_language('lv', 'Latvian', 'Latviski');
CALL insert_language('mg', 'Malagasy', 'مَلَغَسِ');
CALL insert_language('mh', 'Marshallese', 'Kajin M̧ajeļ');
CALL insert_language('mi', 'Maori', 'reo Māori');
CALL insert_language('mk', 'Macedonian', 'Македонски');
CALL insert_language('ml', 'Malayalam', 'മലയാളം');
CALL insert_language('mn', 'Mongolian', 'Монгол хэл');
CALL insert_language('mr', 'Marathi', 'मराठी');
CALL insert_language('ms', 'Malay', 'بهاس ملايو');
CALL insert_language('mt', 'Maltese', 'Malti');
CALL insert_language('my', 'Burmese', 'မြန်မာစာ');
CALL insert_language('na', 'Nauru', 'dorerin Naoe');
CALL insert_language('nb', 'Norwegian Bokmål', 'Norsk bokmål');
CALL insert_language('nd', 'North Ndebele', 'saseNyakatho');
CALL insert_language('ne', 'Nepali', 'नेपाली');
CALL insert_language('ng', 'Ndonga', 'Oshiwambo');
CALL insert_language('nl', 'Dutch', 'Nederlands');
CALL insert_language('nn', 'Norwegian Nynorsk', 'Norsk nynorsk');
CALL insert_language('no', 'Norwegian', 'Norsk');
CALL insert_language('nr', 'South Ndebele', 'sakwaNdzundza');
CALL insert_language('nv', 'Navajo', 'Diné bizaad');
CALL insert_language('ny', 'Chichewa', 'Chi-Chewa');
CALL insert_language('oc', 'Occitan', 'Occitan');
CALL insert_language('oj', 'Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ');
CALL insert_language('om', 'Oromo', 'afaan Oromoo');
CALL insert_language('or', 'Oriya', 'ଓଡ଼ିଆ');
CALL insert_language('os', 'Ossetian', 'дигорон Ӕвзаг');
CALL insert_language('pa', 'Punjabi', 'ਪੰਜਾਬੀ');
CALL insert_language('pi', 'Pali', 'पालि');
CALL insert_language('pl', 'Polish', 'Polski');
CALL insert_language('ps', 'Pashto', 'پښتو');
CALL insert_language('pt', 'Portuguese', 'Português');
CALL insert_language('qu', 'Quechua', 'Runa Simi');
CALL insert_language('rm', 'Romansh', 'Rumantsch');
CALL insert_language('rn', 'Kirundi', 'Ikirundi');
CALL insert_language('ro', 'Romanian', 'Română');
CALL insert_language('ru', 'Russian', 'Русский язык');
CALL insert_language('rw', 'Kinyarwanda', 'Ikinyarwanda');
CALL insert_language('sa', 'Sanskrit', 'संस्कृतम्');
CALL insert_language('sc', 'Sardinian', 'Sardu');
CALL insert_language('sd', 'Sindhi', 'سنڌي');
CALL insert_language('se', 'Northern Sami', 'Davvisámegiella');
CALL insert_language('sg', 'Sango', 'yângâ tî sängö');
CALL insert_language('si', 'Sinhala', 'සිංහල');
CALL insert_language('sk', 'Slovak', 'Slovenčina');
CALL insert_language('sl', 'Slovenian', 'Slovenščina');
CALL insert_language('sm', 'Samoan', 'gagana Sāmoa');
CALL insert_language('sn', 'Shona', 'chiShona');
CALL insert_language('so', 'Somali', 'Soomaali');
CALL insert_language('sq', 'Albanian', 'Shqip');
CALL insert_language('sr', 'Serbian', 'Српски');
CALL insert_language('ss', 'Swati', 'siSwati');
CALL insert_language('st', 'Southern Sotho', 'Sesotho');
CALL insert_language('su', 'Sundanese', 'Basa Sunda');
CALL insert_language('sv', 'Swedish', 'Svenska');
CALL insert_language('sw', 'Swahili', 'Kiswahili');
CALL insert_language('ta', 'Tamil', 'தமிழ்');
CALL insert_language('te', 'Telugu', 'తెలుగు');
CALL insert_language('tg', 'Tajik', 'тоҷикӣ');
CALL insert_language('th', 'Thai', 'ภาษาไทย');
CALL insert_language('ti', 'Tigrinya', 'ትግርኛ');
CALL insert_language('tk', 'Turkmen', 'Türkmençe');
CALL insert_language('tl', 'Tagalog', 'Wikang Tagalog');
CALL insert_language('tn', 'Tswana', 'Setswana');
CALL insert_language('to', 'Tonga', 'lea faka-Tonga');
CALL insert_language('tr', 'Turkish', 'Türkçe');
CALL insert_language('ts', 'Tsonga', 'Xitsonga');
CALL insert_language('tt', 'Tatar', 'Татар теле');
CALL insert_language('tw', 'Twi', 'Twi');
CALL insert_language('ty', 'Tahitian', 'Reo Mā`ohi');
CALL insert_language('ug', 'Uighur', 'ئۇيغۇرچە');
CALL insert_language('uk', 'Ukrainian', 'Українська');
CALL insert_language('ur', 'Urdu', 'اردو');
CALL insert_language('uz', 'Uzbek', 'Oʻzbek tili');
CALL insert_language('ve', 'Venda', 'Tshivenḓa');
CALL insert_language('vi', 'Vietnamese', 'Tiếng Việt');
CALL insert_language('vo', 'Volapük', 'Volapük');
CALL insert_language('wa', 'Walloon', 'Walon');
CALL insert_language('wo', 'Wolof', 'وࣷلࣷفْ');
CALL insert_language('xh', 'Xhosa', 'isiXhosa');
CALL insert_language('yi', 'Yiddish', 'ייִדיש');
CALL insert_language('yo', 'Yoruba', 'èdè Yorùbá');
CALL insert_language('za', 'Zhuang', '話僮');
CALL insert_language('zh', 'Chinese', '中文');
CALL insert_language('zu', 'Zulu', 'isiZulu');
