-- Use the database
USE smartcooking;

CALL insert_language('af', 'Afrikaans', 'Afrikaans');
CALL insert_language('sq', 'Albanian', 'Shqip');
CALL insert_language('am', 'Amharic', 'አማርኛ');
CALL insert_language('ar', 'Arabic', 'العربية');
CALL insert_language('hy', 'Armenian', 'Հայերեն');
CALL insert_language('az', 'Azerbaijani', 'Azərbaycanca');
CALL insert_language('eu', 'Basque', 'Euskara');
CALL insert_language('be', 'Belarusian', 'Беларуская');
CALL insert_language('bn', 'Bengali', 'বাংলা');
CALL insert_language('bs', 'Bosnian', 'Bosanski');
CALL insert_language('bg', 'Bulgarian', 'Български');
CALL insert_language('ca', 'Catalan', 'Català');
CALL insert_language('ceb', 'Cebuano', 'Cebuano');
CALL insert_language('ny', 'Chichewa', 'Chichewa');
CALL insert_language('zh', 'Chinese (Simplified)', '中文 (简体)');
CALL insert_language('co', 'Corsican', 'Corsu');
CALL insert_language('hr', 'Croatian', 'Hrvatski');
CALL insert_language('cs', 'Czech', 'Čeština');
CALL insert_language('da', 'Danish', 'Dansk');
CALL insert_language('nl', 'Dutch', 'Nederlands');
CALL insert_language('en', 'English', 'English');
CALL insert_language('eo', 'Esperanto', 'Esperanto');
CALL insert_language('et', 'Estonian', 'Eesti');
CALL insert_language('tl', 'Filipino', 'Filipino');
CALL insert_language('fi', 'Finnish', 'Suomi');
CALL insert_language('fr', 'French', 'Français');
CALL insert_language('fy', 'Frisian', 'Frysk');
CALL insert_language('gl', 'Galician', 'Galego');
CALL insert_language('ka', 'Georgian', 'ქართული');
CALL insert_language('de', 'German', 'Deutsch');
CALL insert_language('el', 'Greek', 'Ελληνικά');
CALL insert_language('gu', 'Gujarati', 'ગુજરાતી');
CALL insert_language('ht', 'Haitian Creole', 'Kreyòl Ayisyen');
CALL insert_language('ha', 'Hausa', 'Hausa');
CALL insert_language('haw', 'Hawaiian', 'ʻŌlelo Hawaiʻi');
CALL insert_language('iw', 'Hebrew', 'עברית');
CALL insert_language('hi', 'Hindi', 'हिन्दी');
CALL insert_language('hmn', 'Hmong', 'Hmong');
CALL insert_language('hu', 'Hungarian', 'Magyar');
CALL insert_language('is', 'Icelandic', 'Íslenska');
CALL insert_language('ig', 'Igbo', 'Igbo');
CALL insert_language('id', 'Indonesian', 'Bahasa Indonesia');
CALL insert_language('ga', 'Irish', 'Gaeilge');
CALL insert_language('it', 'Italian', 'Italiano');
CALL insert_language('ja', 'Japanese', '日本語');
CALL insert_language('jw', 'Javanese', 'Jawa');
CALL insert_language('kn', 'Kannada', 'ಕನ್ನಡ');
CALL insert_language('kk', 'Kazakh', 'Қазақ');
CALL insert_language('km', 'Khmer', 'ភាសាខ្មែរ');
CALL insert_language('ko', 'Korean', '한국어');
CALL insert_language('ku', 'Kurdish (Kurmanji)', 'Kurdî (Kurmancî)');
CALL insert_language('ky', 'Kyrgyz', 'Кыргызча');
CALL insert_language('lo', 'Lao', 'ພາສາລາວ');
CALL insert_language('la', 'Latin', 'Latina');
CALL insert_language('lv', 'Latvian', 'Latviešu');
CALL insert_language('lt', 'Lithuanian', 'Lietuvių');
CALL insert_language('lb', 'Luxembourgish', 'Lëtzebuergesch');
CALL insert_language('mk', 'Macedonian', 'Македонски');
CALL insert_language('mg', 'Malagasy', 'Malagasy');
CALL insert_language('ms', 'Malay', 'Bahasa Melayu');
CALL insert_language('ml', 'Malayalam', 'മലയാളം');
CALL insert_language('mt', 'Maltese', 'Malti');
CALL insert_language('mi', 'Maori', 'Māori');
CALL insert_language('mr', 'Marathi', 'मराठी');
CALL insert_language('mn', 'Mongolian', 'Монгол');
CALL insert_language('my', 'Myanmar (Burmese)', 'မြန်မာ (ဗမာ)');
CALL insert_language('ne', 'Nepali', 'नेपाली');
CALL insert_language('no', 'Norwegian', 'Norsk');
CALL insert_language('ps', 'Pashto', 'پښتو');
CALL insert_language('fa', 'Persian', 'فارسی');
CALL insert_language('pl', 'Polish', 'Polski');
CALL insert_language('pt', 'Portuguese', 'Português');
CALL insert_language('pa', 'Punjabi', 'ਪੰਜਾਬੀ');
CALL insert_language('ro', 'Romanian', 'Română');
CALL insert_language('ru', 'Russian', 'Русский');
CALL insert_language('sm', 'Samoan', 'Gagana Samoa');
CALL insert_language('gd', 'Scots Gaelic', 'Gàidhlig');
CALL insert_language('sr', 'Serbian', 'Српски');
CALL insert_language('st', 'Sesotho', 'Sesotho');
CALL insert_language('sn', 'Shona', 'Shona');
CALL insert_language('sd', 'Sindhi', 'سنڌي');
CALL insert_language('si', 'Sinhala', 'සිංහල');
CALL insert_language('sk', 'Slovak', 'Slovenčina');
CALL insert_language('sl', 'Slovenian', 'Slovenščina');
CALL insert_language('so', 'Somali', 'Soomaali');
CALL insert_language('es', 'Spanish', 'Español');
CALL insert_language('su', 'Sundanese', 'Basa Sunda');
CALL insert_language('sw', 'Swahili', 'Kiswahili');
CALL insert_language('sv', 'Swedish', 'Svenska');
CALL insert_language('tg', 'Tajik', 'Тоҷикӣ');
CALL insert_language('ta', 'Tamil', 'தமிழ்');
CALL insert_language('te', 'Telugu', 'తెలుగు');
CALL insert_language('th', 'Thai', 'ไทย');
CALL insert_language('tr', 'Turkish', 'Türkçe');
CALL insert_language('uk', 'Ukrainian', 'Українська');
CALL insert_language('ur', 'Urdu', 'اردو');
CALL insert_language('uz', 'Uzbek', 'Oʻzbek');
CALL insert_language('vi', 'Vietnamese', 'Tiếng Việt');
CALL insert_language('cy', 'Welsh', 'Cymraeg');
CALL insert_language('xh', 'Xhosa', 'IsiXhosa');
CALL insert_language('yi', 'Yiddish', 'ייִדיש');
CALL insert_language('yo', 'Yoruba', 'Yorùbá');
CALL insert_language('zu', 'Zulu', 'IsiZulu');
